# Generated by Django 5.1.1 on 2024-10-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0002_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="blog",
        ),
        migrations.AddField(
            model_name="tag",
            name="blog",
            field=models.ManyToManyField(related_name="tags", to="BlogApp.blog"),
        ),
    ]
