# Generated by Django 5.1.1 on 2024-10-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0003_remove_tag_blog_tag_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="blog",
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="BlogApp.tag"),
        ),
    ]
